// Deploy Config Generator — produces ready-to-use config files from a StackProfile
// Supports Fly.io, Cloudflare Workers, Cloudflare Pages, and generates
// Dockerfiles, health endpoints, and MCP manifests

import { logger } from '@uaip/utils'
import type { StackProfile, DeployPlatform, GeneratedConfigs } from '@uaip/types'

export class ConfigGenerator {
  generate(profile: StackProfile, platform: DeployPlatform, subdomain: string): GeneratedConfigs {
    logger.info('Generating deploy configs', { platform, subdomain, framework: profile.framework })

    let files: Record<string, string> = {}

    switch (platform) {
      case 'fly':
        files = this.generateFlyConfig(profile, subdomain)
        break
      case 'cloudflare-workers':
        files = this.generateCFWorkersConfig(profile, subdomain)
        break
      case 'cloudflare-pages':
        files = this.generateCFPagesConfig(profile, subdomain)
        break
    }

    // Generate Dockerfile if missing
    if (!profile.hasDockerfile && platform === 'fly') {
      files['Dockerfile'] = this.generateDockerfile(profile)
    }

    // Generate health endpoint if missing
    if (!profile.hasHealthEndpoint) {
      const healthCode = this.generateHealthEndpoint(profile)
      if (healthCode) {
        files['_generated_health_endpoint.txt'] = healthCode
      }
    }

    // Always generate MCP manifest
    files['.well-known/mcp.json'] = JSON.stringify(this.generateMCPManifest(profile, subdomain), null, 2)

    return { files, stackProfile: profile, platform, subdomain }
  }

  generateFlyConfig(profile: StackProfile, subdomain: string): Record<string, string> {
    const port = profile.port ?? 3000
    const files: Record<string, string> = {}

    // Build fly.toml
    const envBlock = profile.envVars.length > 0
      ? `\n[env]\n${profile.envVars.filter(v => !v.includes('SECRET') && !v.includes('PASSWORD') && !v.includes('KEY')).map(v => `  ${v} = ""`).join('\n')}\n`
      : ''

    const dbChecks = profile.databases.includes('postgres')
      ? `\n[[services.tcp_checks]]\n  grace_period = "10s"\n  interval = "15s"\n  timeout = "2s"\n`
      : ''

    files['fly.toml'] = `# Generated by TARDIS Onboarding Engine
app = "${subdomain}"
primary_region = "iad"

[build]

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
${envBlock}
[checks]
  [checks.health]
    type = "http"
    port = ${port}
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
${dbChecks}`

    return files
  }

  generateCFWorkersConfig(profile: StackProfile, subdomain: string): Record<string, string> {
    const files: Record<string, string> = {}

    const kvBindings = profile.databases.includes('redis')
      ? `\n[[kv_namespaces]]\nbinding = "KV"\nid = ""\n`
      : ''

    const d1Bindings = profile.databases.includes('postgres') || profile.databases.includes('sqlite')
      ? `\n[[d1_databases]]\nbinding = "DB"\ndatabase_name = "${subdomain}-db"\ndatabase_id = ""\n`
      : ''

    files['wrangler.toml'] = `# Generated by TARDIS Onboarding Engine
name = "${subdomain}"
main = "src/index.ts"
compatibility_date = "${new Date().toISOString().split('T')[0]}"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
${kvBindings}${d1Bindings}
[observability]
enabled = true
`

    return files
  }

  generateCFPagesConfig(profile: StackProfile, subdomain: string): Record<string, string> {
    const files: Record<string, string> = {}

    files['_headers'] = `# Generated by TARDIS Onboarding Engine
/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/.well-known/*
  Access-Control-Allow-Origin: *
  Content-Type: application/json
`

    files['_redirects'] = `# Generated by TARDIS Onboarding Engine
/api/*  https://${subdomain}-api.fly.dev/api/:splat  200
`

    return files
  }

  generateDockerfile(profile: StackProfile): string {
    switch (profile.runtime) {
      case 'bun':
        return this.generateBunDockerfile(profile)
      case 'node':
        return this.generateNodeDockerfile(profile)
      case 'deno':
        return this.generateDenoDockerfile(profile)
      case 'python':
        return this.generatePythonDockerfile(profile)
      case 'go':
        return this.generateGoDockerfile(profile)
      case 'rust':
        return this.generateRustDockerfile(profile)
      case 'ruby':
        return this.generateRubyDockerfile(profile)
      case 'jvm':
        return this.generateJvmDockerfile(profile)
      case 'beam':
        return this.generateBeamDockerfile(profile)
      default:
        return this.generateNodeDockerfile(profile)
    }
  }

  generateHealthEndpoint(profile: StackProfile): string {
    switch (profile.framework) {
      case 'elysia':
        return `// Add this to your Elysia app
import { Elysia } from 'elysia'

app.get('/health', () => ({
  status: 'ok',
  service: '${profile.framework}',
  timestamp: new Date().toISOString(),
  uptime: process.uptime(),
}))`

      case 'express':
        return `// Add this to your Express app
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  });
});`

      case 'fastify':
        return `// Add this to your Fastify app
fastify.get('/health', async () => ({
  status: 'ok',
  timestamp: new Date().toISOString(),
  uptime: process.uptime(),
}));`

      case 'nextjs':
        return `// Create this file at: pages/api/health.ts (or app/api/health/route.ts)
export async function GET() {
  return Response.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
  });
}`

      case 'hono':
        return `// Add this to your Hono app
app.get('/health', (c) => c.json({
  status: 'ok',
  timestamp: new Date().toISOString(),
}));`

      case 'fastapi':
        return `# Add this to your FastAPI app
@app.get("/health")
async def health():
    return {"status": "ok", "timestamp": datetime.utcnow().isoformat()}`

      case 'django':
        return `# Add this to your urls.py and create a health view
# urls.py: path('health/', health_view)
from django.http import JsonResponse
import datetime

def health_view(request):
    return JsonResponse({"status": "ok", "timestamp": datetime.datetime.utcnow().isoformat()})`

      case 'flask':
        return `# Add this to your Flask app
@app.route('/health')
def health():
    return jsonify({"status": "ok", "timestamp": datetime.utcnow().isoformat()})`

      case 'gin':
        return `// Add this to your Gin router
r.GET("/health", func(c *gin.Context) {
    c.JSON(200, gin.H{
        "status": "ok",
        "timestamp": time.Now().UTC().Format(time.RFC3339),
    })
})`

      case 'rails':
        return `# Add to config/routes.rb:
# get '/health', to: 'health#show'
# Create app/controllers/health_controller.rb:
class HealthController < ApplicationController
  skip_before_action :authenticate_user!, raise: false

  def show
    render json: { status: 'ok', timestamp: Time.now.utc.iso8601 }
  end
end`

      case 'phoenix':
        return `# Add to router.ex:
# get "/health", HealthController, :show
# Create lib/app_web/controllers/health_controller.ex:
defmodule AppWeb.HealthController do
  use AppWeb, :controller

  def show(conn, _params) do
    json(conn, %{status: "ok", timestamp: DateTime.utc_now() |> DateTime.to_iso8601()})
  end
end`

      case 'actix':
      case 'axum':
        return `// Add this health endpoint to your router
async fn health() -> impl IntoResponse {
    Json(serde_json::json!({
        "status": "ok",
        "timestamp": chrono::Utc::now().to_rfc3339()
    }))
}`

      default:
        if (profile.language === 'typescript' || profile.language === 'javascript') {
          return `// Generic health endpoint
// Adapt to your framework
export function healthHandler() {
  return {
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  };
}`
        }
        return ''
    }
  }

  generateMCPManifest(profile: StackProfile, subdomain: string): object {
    const tools = profile.apiRoutes.map((route) => {
      const [method, path] = route.split(' ')
      const toolName = this.routeToToolName(method ?? 'GET', path ?? '/')
      return {
        name: toolName,
        description: `${method} ${path}`,
        inputSchema: {
          type: 'object',
          properties: {},
        },
        endpoint: {
          method: method?.toLowerCase() ?? 'get',
          path: path ?? '/',
        },
      }
    })

    // Add health tool
    tools.push({
      name: 'health_check',
      description: 'Check service health status',
      inputSchema: { type: 'object', properties: {} },
      endpoint: { method: 'get', path: '/health' },
    })

    return {
      schema_version: '1.0.0',
      server: {
        name: subdomain,
        version: '1.0.0',
        transport: 'streamable-http',
        url: `https://${subdomain}.fly.dev`,
      },
      capabilities: {
        tools,
      },
      metadata: {
        language: profile.language,
        runtime: profile.runtime,
        framework: profile.framework,
        generatedAt: new Date().toISOString(),
        generatedBy: 'tardis-onboarding-engine',
      },
    }
  }

  // --- Private Dockerfile generators ---

  private generateBunDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 3000
    return `# Generated by TARDIS Onboarding Engine
# Multi-stage Bun build
FROM oven/bun:1 AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile --production

# Build stage
FROM base AS build
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile
COPY . .
${profile.buildCommand ? `RUN ${profile.buildCommand}` : ''}

# Production stage
FROM base AS production
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/${profile.buildCommand ? 'dist' : '.'} ./${profile.buildCommand ? 'dist' : ''}
COPY --from=build /app/package.json ./

ENV NODE_ENV=production
EXPOSE ${port}

CMD ["bun", "run", "${profile.startCommand ?? 'start'}"]
`
  }

  private generateNodeDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 3000
    return `# Generated by TARDIS Onboarding Engine
# Multi-stage Node.js build
FROM node:20-alpine AS base
WORKDIR /app

# Install dependencies
FROM base AS deps
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN \\
  if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile --prod; \\
  elif [ -f yarn.lock ]; then yarn install --frozen-lockfile --production; \\
  elif [ -f package-lock.json ]; then npm ci --omit=dev; \\
  else npm install --omit=dev; fi

# Build stage
FROM base AS build
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN \\
  if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\
  elif [ -f yarn.lock ]; then yarn install --frozen-lockfile; \\
  elif [ -f package-lock.json ]; then npm ci; \\
  else npm install; fi
COPY . .
${profile.buildCommand ? `RUN npm run build` : ''}

# Production stage
FROM node:20-alpine AS production
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app .

ENV NODE_ENV=production
EXPOSE ${port}

CMD ["node", "${profile.framework === 'nextjs' ? 'node_modules/.bin/next start' : 'dist/index.js'}"]
`
  }

  private generateDenoDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 8000
    return `# Generated by TARDIS Onboarding Engine
FROM denoland/deno:latest
WORKDIR /app

COPY . .
RUN deno cache main.ts

ENV DENO_DEPLOYMENT_ID=production
EXPOSE ${port}

CMD ["deno", "run", "--allow-all", "main.ts"]
`
  }

  private generatePythonDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 8000
    const hasPoetry = profile.buildCommand?.includes('poetry') ?? false
    const hasPipenv = profile.buildCommand?.includes('pipenv') ?? false

    let installStep: string
    if (hasPoetry) {
      installStep = `RUN pip install poetry && poetry config virtualenvs.create false && poetry install --no-dev`
    } else if (hasPipenv) {
      installStep = `RUN pip install pipenv && pipenv install --system --deploy`
    } else {
      installStep = `COPY requirements.txt ./\nRUN pip install --no-cache-dir -r requirements.txt`
    }

    const startCmd = profile.startCommand ?? `uvicorn main:app --host 0.0.0.0 --port ${port}`

    return `# Generated by TARDIS Onboarding Engine
FROM python:3.12-slim AS base
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

${installStep}

COPY . .

EXPOSE ${port}

CMD [${startCmd.split(' ').map(s => `"${s}"`).join(', ')}]
`
  }

  private generateGoDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 8080
    return `# Generated by TARDIS Onboarding Engine
# Multi-stage Go build
FROM golang:1.22-alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server .

# Production stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=build /app/server .

EXPOSE ${port}

CMD ["./server"]
`
  }

  private generateRustDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 8080
    return `# Generated by TARDIS Onboarding Engine
# Multi-stage Rust build
FROM rust:1.77 AS build
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs && cargo build --release && rm -rf src

COPY . .
RUN cargo build --release

# Production stage
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=build /app/target/release/app .

EXPOSE ${port}

CMD ["./app"]
`
  }

  private generateRubyDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 3000
    return `# Generated by TARDIS Onboarding Engine
FROM ruby:3.3-slim AS base
WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test

COPY . .

${profile.framework === 'rails' ? 'RUN bundle exec rails assets:precompile' : ''}

EXPOSE ${port}

CMD ["bundle", "exec", "${profile.framework === 'rails' ? 'rails server -b 0.0.0.0' : 'ruby app.rb'}"]
`
  }

  private generateJvmDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 8080
    const isGradle = profile.buildCommand?.includes('gradle') ?? false

    const buildStage = isGradle
      ? `FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle build -x test --no-daemon`
      : `FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY . .
RUN mvn clean package -DskipTests`

    const jarPath = isGradle ? 'build/libs/*.jar' : 'target/*.jar'

    return `# Generated by TARDIS Onboarding Engine
${buildStage}

# Production stage
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /app/${jarPath} app.jar

EXPOSE ${port}

CMD ["java", "-jar", "app.jar"]
`
  }

  private generateBeamDockerfile(profile: StackProfile): string {
    const port = profile.port ?? 4000
    return `# Generated by TARDIS Onboarding Engine
FROM elixir:1.16-alpine AS build
WORKDIR /app

ENV MIX_ENV=prod

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
RUN mix deps.get --only prod && mix deps.compile

COPY . .
RUN mix compile && mix release

# Production stage
FROM alpine:latest
RUN apk add --no-cache libstdc++ openssl ncurses-libs
WORKDIR /app

COPY --from=build /app/_build/prod/rel/app ./

EXPOSE ${port}

CMD ["bin/app", "start"]
`
  }

  private routeToToolName(method: string, path: string): string {
    const cleanPath = path
      .replace(/^\/api\/v\d+\//, '')
      .replace(/^\//, '')
      .replace(/\//g, '_')
      .replace(/[:{}[\]]/g, '')
      .replace(/_+/g, '_')
      .replace(/_$/, '')

    return `${method.toLowerCase()}_${cleanPath || 'root'}`
  }
}
