packages:
  - apps/*
  - packages/*
  - backend/services/*
  - backend/shared/*

catalog:
  typescript: ^5.8.3
  zod: 3.25.67
  eslint: ^9.29.0
  ts-node: ^10.9.2
  '@eslint/js': ^9.29.0
  rimraf: ^6.0.1
  '@typescript-eslint/eslint-plugin': ^8.34.1
  '@typescript-eslint/parser': ^8.34.1
  typescript-eslint: ^8.34.1

catalogs:
  frontend:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    '@vitejs/plugin-react-swc': ^3.10.2
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    '@types/node': ^22.13.14
    react-hook-form: ^7.58.1
    react-router-dom: ^7.6.2
    react-day-picker: ^9.7.0
    react-resizable-panels: ^3.0.3
    '@radix-ui/react-accordion': ^1.2.11
    '@radix-ui/react-alert-dialog': ^1.1.14
    '@radix-ui/react-aspect-ratio': ^1.1.7
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.2
    '@radix-ui/react-collapsible': ^1.1.11
    '@radix-ui/react-context-menu': ^2.2.15
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-hover-card': ^1.1.14
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-menubar': ^1.1.15
    '@radix-ui/react-navigation-menu': ^1.2.13
    '@radix-ui/react-popover': ^1.1.14
    '@radix-ui/react-progress': ^1.1.7
    '@radix-ui/react-radio-group': ^1.3.7
    '@radix-ui/react-scroll-area': ^1.2.9
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slider': ^1.3.5
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-switch': ^1.2.5
    '@radix-ui/react-tabs': ^1.1.12
    '@radix-ui/react-toast': ^1.2.14
    '@radix-ui/react-toggle': ^1.1.9
    '@radix-ui/react-toggle-group': ^1.1.10
    '@radix-ui/react-tooltip': ^1.2.7
    '@heroicons/react': ^2.2.0
    '@tanstack/react-query': ^5.80.10
    '@tanstack/react-virtual': ^3.13.10
    lucide-react: ^0.518.0
    embla-carousel-react: ^8.6.0
    socket.io-client: 4.8.1
    '@hookform/resolvers': ^5.1.1
    axios: ^1.10.0
  backend:
    express: ^5.1.0
    '@types/express': ^5.0.3
    express-rate-limit: ^7.5.0
    express-validator: ^7.2.1
    express-slow-down: ^2.1.0
    socket.io: ^4.8.1
    typeorm: ^0.3.24
    '@types/node': ^22.13.14
    '@types/cors': ^2.8.18
    typescript: ^5.8.3
    zod: ^3.25.67
    dotenv: ^16.4.7
    cors: ^2.8.5
    nodemon: ^3.1.9
    ts-node: ^10.9.2
    axios: ^1.10.0
    winston: ^3.17.0
    tsx: ^4.20.3
    helmet: ^8.1.0
    compression: ^1.8.0
    '@types/compression': ^1.8.1
    prom-client: ^15.1.3
    jest: ^30.0.2
    '@types/jest': ^30.0.0
    ts-jest: ^29.4.0
    tsc-alias: ^1.8.16
    bcrypt: ^6.0.0
    '@types/bcrypt': ^5.0.2
    pg: ^8.16.1
    '@types/pg': ^8.15.4
    jsonwebtoken: ^9.0.2
    '@types/jsonwebtoken': ^9.0.10
    uuid: ^11.1.0
    ws: ^8.18.2
    '@types/ws': 8.18.1
    amqplib: ^0.10.8
    '@types/amqplib': ^0.10.7
    neo4j-driver: ^5.28.1
    multer: ^2.0.1
    '@types/multer': ^1.4.12
  dev:
    esbuild: ^0.24.2
    vite: ^6.0.7
    vitest: ^3.2.4
    '@vitest/ui': ^3.2.4
    prettier: ^3.4.2
    '@types/eslint': ^9.7.0
    concurrently: ^9.1.1
    cross-env: ^7.0.3

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - unrs-resolver
