import { Queue, Worker, type Job } from 'bullmq';
import { logger } from '@uaip/utils';
import { config } from '@uaip/config';
import type { TriagedIncident } from '../types/triage.js';
import type { TicketRef } from '../types/ticketing_adapter.js';
import { JiraTicketingAdapter } from './jira_ticketing_adapter.js';

const OIE_INCIDENTS_TOPIC = 'oie.incidents.triaged';

function getRedisOptions() {
  return {
    host: config.redis?.host ?? 'localhost',
    port: config.redis?.port ?? 6379,
    password: config.redis?.password ?? undefined,
    maxRetriesPerRequest: null as null,
    enableReadyCheck: false,
  };
}

function severityToPriority(severity: string): 'Highest' | 'High' | 'Medium' | 'Low' | 'Lowest' {
  switch (severity) {
    case 'critical': return 'Highest';
    case 'high': return 'High';
    case 'medium': return 'Medium';
    case 'low': return 'Low';
    default: return 'Medium';
  }
}

function buildTicketDescription(incident: TriagedIncident): string {
  const signozUrl = `${process.env.SIGNOZ_API_URL ?? 'http://localhost:3301'}/traces?service=${incident.service}`;
  const sentryUrl = `${process.env.SENTRY_API_URL ?? 'http://localhost:9000'}/${process.env.SENTRY_ORG ?? 'sentry'}/${process.env.SENTRY_PROJECT ?? 'navratna'}/issues/?query=${encodeURIComponent(incident.errorCode)}`;

  return [
    `*Context*`,
    `Service: ${incident.service}`,
    `Error Code: ${incident.errorCode}`,
    `Category: ${incident.classification.category}`,
    `Severity: ${incident.classification.severity}`,
    `Occurrences (1h): ${incident.occurrences1h}`,
    `Occurrences (24h): ${incident.occurrences24h}`,
    `First Seen: ${incident.firstSeenAt.toISOString()}`,
    `Last Seen: ${incident.lastSeenAt.toISOString()}`,
    ``,
    `*What*`,
    incident.message,
    ``,
    `Triage Reasoning: ${incident.classification.reasoning}`,
    ``,
    `*Deep Links*`,
    `SigNoz Traces: ${signozUrl}`,
    `Sentry Issue: ${sentryUrl}`,
    ``,
    `*Auto-generated by OIE* (PM-176)`,
  ].join('\n');
}

export class AutoJiraService {
  private worker: Worker | null = null;
  private jira: JiraTicketingAdapter;
  private projectKey: string;

  constructor(projectKey?: string) {
    this.jira = new JiraTicketingAdapter();
    this.projectKey = projectKey ?? process.env.JIRA_PROJECT_KEY ?? 'PM';
  }

  async start(): Promise<void> {
    await this.jira.initialize({});

    const connection = getRedisOptions();

    this.worker = new Worker(
      OIE_INCIDENTS_TOPIC,
      async (job: Job) => this.processIncident(job),
      { connection, concurrency: 2 },
    );

    this.worker.on('failed', (job, err) => {
      logger.error('AutoJiraService: job failed', { jobId: job?.id, error: err.message });
    });

    logger.info('AutoJiraService started', { projectKey: this.projectKey });
  }

  private async processIncident(job: Job): Promise<void> {
    const incident = job.data as TriagedIncident;

    if (incident.classification.action !== 'create_ticket') {
      return;
    }

    const existingRef = await this.findExistingTicket(incident.errorCode, incident.service);
    if (existingRef) {
      const comment = [
        `*OIE Update* — Incident recurred`,
        `Occurrences (1h): ${incident.occurrences1h}, (24h): ${incident.occurrences24h}`,
        `Last seen: ${incident.lastSeenAt.toISOString()}`,
      ].join('\n');
      await this.jira.addComment(existingRef, comment);
      logger.info('AutoJiraService: updated existing ticket', { key: existingRef.key, incidentId: incident.id });
      return;
    }

    try {
      const created = await this.jira.createIssue({
        projectKey: this.projectKey,
        summary: `[OIE] ${incident.service}: ${incident.errorCode} — ${incident.classification.severity}`,
        description: buildTicketDescription(incident),
        issueType: 'Bug',
        priority: severityToPriority(incident.classification.severity),
        labels: ['oie-auto', `service:${incident.service}`, `category:${incident.classification.category}`],
      });

      logger.info('AutoJiraService: ticket created', {
        key: created.ref.key,
        incidentId: incident.id,
        service: incident.service,
        errorCode: incident.errorCode,
      });
    } catch (err) {
      logger.error('AutoJiraService: failed to create ticket', {
        incidentId: incident.id,
        error: err instanceof Error ? err.message : err,
      });
      throw err;
    }
  }

  private async findExistingTicket(errorCode: string, service: string): Promise<TicketRef | undefined> {
    try {
      const results = await this.jira.searchIssues({
        jql: `project = "${this.projectKey}" AND labels = "oie-auto" AND labels = "service:${service}" AND summary ~ "${errorCode}" AND status != Done`,
        maxResults: 1,
      });
      return results[0]?.ref;
    } catch {
      return undefined;
    }
  }

  async stop(): Promise<void> {
    await this.worker?.close();
    await this.jira.shutdown();
    logger.info('AutoJiraService stopped');
  }
}
