import { randomUUID } from 'node:crypto'
import { EventBusService } from '@uaip/shared-services'
import type {
  BoardProvider,
  DecomposedStory,
  EventBusMessage,
  RepoContext,
  SolutionDesign,
} from '@uaip/types'
import { logger, InternalServerError } from '@uaip/utils'

const DEVAGENT_PR_CREATED_EVENT = 'rdlo.devagent.pr.created'
const DEVAGENT_CODE_REVIEW_EVENT = 'rdlo.devagent.code.review'

interface PRGenerationResult {
  prUrl: string
  branch: string
  storyId: string
  title: string
  filesChanged: number
  lintPassed: boolean
  testsPassed: boolean
}

interface CodeReviewResult {
  approved: boolean
  comments: string[]
  conventionViolations: string[]
}

export class DevAgentService {
  constructor(private readonly eventBusService: EventBusService) {}

  async executeStory(
    story: DecomposedStory,
    repoCtx: RepoContext,
    design: SolutionDesign,
    boardProvider: BoardProvider,
    boardStoryId: string,
    githubToken: string
  ): Promise<PRGenerationResult> {
    const branch = this.generateBranchName(boardStoryId)

    await this.eventBusService.publish('rdlo.devagent.execute.start', {
      storyTitle: story.title,
      branch,
      repoUrl: repoCtx.source,
      affectedFiles: story.affectedFiles,
    })

    const reviewResult = await this.runCodeReview(story, repoCtx, design)

    if (!reviewResult.approved && reviewResult.conventionViolations.length > 0) {
      logger.warn('Code review found convention violations, proceeding with warnings', {
        storyTitle: story.title,
        violations: reviewResult.conventionViolations,
      })
    }

    const prDescription = this.buildPRDescription(story, design, reviewResult)

    const prUrl = await this.createGitHubPR({
      owner: this.extractOwner(repoCtx.source),
      repo: this.extractRepo(repoCtx.source),
      token: githubToken,
      title: `rdlo: ${story.title}`,
      body: prDescription,
      head: branch,
      base: 'main',
    })

    await boardProvider.linkPR(boardStoryId, prUrl)

    const result: PRGenerationResult = {
      prUrl,
      branch,
      storyId: boardStoryId,
      title: story.title,
      filesChanged: story.affectedFiles.length,
      lintPassed: reviewResult.conventionViolations.length === 0,
      testsPassed: reviewResult.approved,
    }

    await this.eventBusService.publish(DEVAGENT_PR_CREATED_EVENT, {
      prUrl,
      branch,
      storyTitle: story.title,
      filesChanged: result.filesChanged,
    })

    logger.info('DevAgent PR created', {
      prUrl,
      branch,
      storyTitle: story.title,
      filesChanged: result.filesChanged,
    })

    return result
  }

  private async runCodeReview(
    story: DecomposedStory,
    repoCtx: RepoContext,
    design: SolutionDesign
  ): Promise<CodeReviewResult> {
    const violations: string[] = []
    const comments: string[] = []

    if (repoCtx.commitFormat) {
      comments.push(`Commit format convention: ${repoCtx.commitFormat}`)
    }

    if (story.estimatedLOC > 300) {
      violations.push(`Story exceeds 300 LOC limit (estimated: ${story.estimatedLOC})`)
    }

    for (const file of design.affectedFiles) {
      if (file.path.includes('..')) {
        violations.push(`Suspicious path traversal in file: ${file.path}`)
      }
    }

    await this.eventBusService.publish(DEVAGENT_CODE_REVIEW_EVENT, {
      storyTitle: story.title,
      approved: violations.length === 0,
      violationCount: violations.length,
      commentCount: comments.length,
    })

    return {
      approved: violations.length === 0,
      comments,
      conventionViolations: violations,
    }
  }

  private buildPRDescription(
    story: DecomposedStory,
    design: SolutionDesign,
    review: CodeReviewResult
  ): string {
    const sections: string[] = []

    sections.push(`## Context\n\n${design.summary}`)
    sections.push(`## Story\n\n**${story.title}**\n\n${story.description}`)
    sections.push(
      `## Affected Files\n\n${story.affectedFiles.map((f) => `- \`${f}\``).join('\n')}`
    )

    if (design.risks.length > 0) {
      sections.push(
        `## Risks\n\n${design.risks.map((r) => `- **${r.severity}**: ${r.description} → ${r.mitigation}`).join('\n')}`
      )
    }

    if (review.comments.length > 0) {
      sections.push(
        `## Review Notes\n\n${review.comments.map((c) => `- ${c}`).join('\n')}`
      )
    }

    if (review.conventionViolations.length > 0) {
      sections.push(
        `## ⚠️ Convention Warnings\n\n${review.conventionViolations.map((v) => `- ${v}`).join('\n')}`
      )
    }

    sections.push(
      `## Metadata\n\n` +
      `- **Tier**: ${design.tier}\n` +
      `- **Estimated LOC**: ${story.estimatedLOC}\n` +
      `- **Lint**: ${review.conventionViolations.length === 0 ? '✅' : '⚠️'}\n` +
      `- **Auto-generated by**: RDLO DevAgent`
    )

    return sections.join('\n\n---\n\n')
  }

  private async createGitHubPR(params: {
    owner: string
    repo: string
    token: string
    title: string
    body: string
    head: string
    base: string
  }): Promise<string> {
    const response = await fetch(
      `https://api.github.com/repos/${params.owner}/${params.repo}/pulls`,
      {
        method: 'POST',
        headers: {
          'Accept': 'application/vnd.github+json',
          'Authorization': `Bearer ${params.token}`,
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: params.title,
          body: params.body,
          head: params.head,
          base: params.base,
        }),
      }
    )

    if (!response.ok) {
      const errorBody = await response.text().catch(() => '<unreadable>')
      throw new InternalServerError(`GitHub PR creation failed: ${response.status} — ${errorBody.slice(0, 500)}`)
    }

    const pr = await response.json() as { html_url: string }
    return pr.html_url
  }

  private generateBranchName(storyId: string): string {
    const sanitized = storyId.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase()
    return `rdlo/story-${sanitized}`
  }

  private extractOwner(repoUrl: string): string {
    const match = repoUrl.match(/github\.com[/:]([^/]+)\//)
    return match?.[1] ?? 'unknown'
  }

  private extractRepo(repoUrl: string): string {
    const match = repoUrl.match(/github\.com[/:]([^/]+)\/([^/.]+)/)
    return match?.[2] ?? 'unknown'
  }
}
