import { EventBusService } from '@uaip/shared-services'
import type {
  BoardProvider,
  DecomposedStory,
  RepoContext,
  SolutionDesign,
} from '@uaip/types'
import { InternalServerError } from '@uaip/utils'

const DEVAGENT_CODE_REVIEW_EVENT = 'rdlo.devagent.code.review'

export interface PRGenerationResult {
  prUrl: string
  branch: string
  storyId: string
  title: string
  filesChanged: number
  lintPassed: boolean
  testsPassed: boolean
}

interface CodeReviewResult {
  approved: boolean
  comments: string[]
  conventionViolations: string[]
}

export class DevAgentService {
  constructor(private readonly eventBusService: EventBusService) {}

  /**
   * NOT IMPLEMENTED.
   *
   * The name promises "execute this story"; the body never wrote a line of code.
   * It derived a branch name, ran a static convention review, and then POSTed to
   * GitHub's create-PR API with `head` set to a branch that was never created,
   * never checked out, and never pushed. The PRGenerationResult it returned was
   * fabricated in the same spirit: `filesChanged` counted the files the story
   * *intended* to touch, and `lintPassed` / `testsPassed` came from that static
   * review rather than from running any linter or test suite.
   *
   * Two things are missing before this can be real: a code-generation step, and a
   * source-control write path (branch, commit, push) ahead of PR creation. Note
   * also that createGitHubPR is hardcoded to api.github.com, which does not fit a
   * Gitea-backed deployment.
   *
   * runCodeReview() and buildPRDescription() below are genuine and are kept —
   * they are usable once there is real work to describe.
   */
  async executeStory(
    _story: DecomposedStory,
    _repoCtx: RepoContext,
    _design: SolutionDesign,
    _boardProvider: BoardProvider,
    boardStoryId: string,
    _githubToken: string
  ): Promise<PRGenerationResult> {
    throw new InternalServerError(
      `DevAgentService.executeStory is not implemented (story ${boardStoryId}). ` +
        `It previously opened a pull request for branch ` +
        `'${this.generateBranchName(boardStoryId)}', which it never created or pushed, ` +
        `and reported fabricated filesChanged/lintPassed/testsPassed. Implement code ` +
        `generation and a branch-and-push path before calling this.`
    )
  }

  private async runCodeReview(
    story: DecomposedStory,
    repoCtx: RepoContext,
    design: SolutionDesign
  ): Promise<CodeReviewResult> {
    const violations: string[] = []
    const comments: string[] = []

    if (repoCtx.commitFormat) {
      comments.push(`Commit format convention: ${repoCtx.commitFormat}`)
    }

    if (story.estimatedLOC > 300) {
      violations.push(`Story exceeds 300 LOC limit (estimated: ${story.estimatedLOC})`)
    }

    for (const file of design.affectedFiles) {
      if (file.path.includes('..')) {
        violations.push(`Suspicious path traversal in file: ${file.path}`)
      }
    }

    await this.eventBusService.publish(DEVAGENT_CODE_REVIEW_EVENT, {
      storyTitle: story.title,
      approved: violations.length === 0,
      violationCount: violations.length,
      commentCount: comments.length,
    })

    return {
      approved: violations.length === 0,
      comments,
      conventionViolations: violations,
    }
  }

  private buildPRDescription(
    story: DecomposedStory,
    design: SolutionDesign,
    review: CodeReviewResult
  ): string {
    const sections: string[] = []

    sections.push(`## Context\n\n${design.summary}`)
    sections.push(`## Story\n\n**${story.title}**\n\n${story.description}`)
    sections.push(
      `## Affected Files\n\n${story.affectedFiles.map((f) => `- \`${f}\``).join('\n')}`
    )

    if (design.risks.length > 0) {
      sections.push(
        `## Risks\n\n${design.risks.map((r) => `- **${r.severity}**: ${r.description} → ${r.mitigation}`).join('\n')}`
      )
    }

    if (review.comments.length > 0) {
      sections.push(
        `## Review Notes\n\n${review.comments.map((c) => `- ${c}`).join('\n')}`
      )
    }

    if (review.conventionViolations.length > 0) {
      sections.push(
        `## ⚠️ Convention Warnings\n\n${review.conventionViolations.map((v) => `- ${v}`).join('\n')}`
      )
    }

    sections.push(
      `## Metadata\n\n` +
      `- **Tier**: ${design.tier}\n` +
      `- **Estimated LOC**: ${story.estimatedLOC}\n` +
      `- **Lint**: ${review.conventionViolations.length === 0 ? '✅' : '⚠️'}\n` +
      `- **Auto-generated by**: RDLO DevAgent`
    )

    return sections.join('\n\n---\n\n')
  }

  private async createGitHubPR(params: {
    owner: string
    repo: string
    token: string
    title: string
    body: string
    head: string
    base: string
  }): Promise<string> {
    const response = await fetch(
      `https://api.github.com/repos/${params.owner}/${params.repo}/pulls`,
      {
        method: 'POST',
        headers: {
          'Accept': 'application/vnd.github+json',
          'Authorization': `Bearer ${params.token}`,
          'X-GitHub-Api-Version': '2022-11-28',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: params.title,
          body: params.body,
          head: params.head,
          base: params.base,
        }),
      }
    )

    if (!response.ok) {
      const errorBody = await response.text().catch(() => '<unreadable>')
      throw new InternalServerError(`GitHub PR creation failed: ${response.status} — ${errorBody.slice(0, 500)}`)
    }

    const pr: { html_url: string } = await response.json()
    return pr.html_url
  }

  private generateBranchName(storyId: string): string {
    const sanitized = storyId.replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase()
    return `rdlo/story-${sanitized}`
  }

  private extractOwner(repoUrl: string): string {
    const match = repoUrl.match(/github\.com[/:]([^/]+)\//)
    return match?.[1] ?? 'unknown'
  }

  private extractRepo(repoUrl: string): string {
    const match = repoUrl.match(/github\.com[/:]([^/]+)\/([^/.]+)/)
    return match?.[2] ?? 'unknown'
  }
}
