import { getIntelligenceDb } from '../drizzle/clients/index';
import { agents, type Agent } from '../../database/drizzle/schemas/intelligence_schema';
import { BaseSeed } from './base_seed';
import {
  AgentRole,
  AgentPersona,
  AgentIntelligenceConfig,
  AgentSecurityContext,
} from '@uaip/types';
import type { InferInsertModel } from 'drizzle-orm';

type AgentInsert = InferInsertModel<typeof agents>;

export class AgentSeed extends BaseSeed {
  private db = getIntelligenceDb();
  private users: { id: string }[] = [];
  private personas: { id: string }[] = [];

  constructor(userIds: string[], personaIds: string[]) {
    super('Agents');
    this.users = userIds.map((id) => ({ id }));
    this.personas = personaIds.map((id) => ({ id }));
  }

  async seed(): Promise<Agent[]> {
    const seedData = await this.getSeedData();

    for (const agent of seedData) {
      await this.db
        .insert(agents)
        .values(agent)
        .onConflictDoNothing();
    }

    return await this.db.select().from(agents);
  }

  private getPersonaIdByRole(_agentRole: string): string {
    return this.personas[0]?.id ?? '00000000-0000-0000-0000-000000000000';
  }

  async getSeedData(): Promise<AgentInsert[]> {
    return [
      {
        name: 'Pro',
        role: AgentRole.ANALYZER,
        personaId: this.getPersonaIdByRole('Pro'),
        legacyPersona: {
          name: 'Pro',
          description: 'Advanced data analysis agent',
          capabilities: ['data-analysis', 'visualization'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'advanced',
          contextWindowSize: 8000,
          decisionThreshold: 0.8,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'high',
          allowedCapabilities: ['data-analysis'],
          restrictedDomains: [],
          approvalRequired: true,
          auditLevel: 'comprehensive',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: ['data-analysis', 'visualization', 'statistical-modeling', 'reporting'],
        capabilityScores: { 'data-analysis': 0.95, visualization: 0.88 },
        performanceMetrics: { averageResponseTime: 2.5, successRate: 0.94, userSatisfaction: 0.89 },
        securityLevel: 'high',
        complianceTags: ['GDPR', 'SOX'],
        configuration: { maxConcurrentOperations: 5, timeoutDuration: 300, retryAttempts: 3 },
        version: '2.1.0',
        deploymentEnvironment: 'production',
        totalOperations: 1250,
        successfulOperations: 1175,
        averageResponseTime: 2.5,
        modelId: 'deepcogito-v1',
        apiType: 'llmstudio',
        temperature: 0.3,
        maxTokens: 4000,
        systemPrompt: 'You are Pro, an advanced data analysis agent.',
        maxConcurrentTools: 5,
      },
      {
        name: 'Taniye',
        role: AgentRole.ORCHESTRATOR,
        personaId: this.getPersonaIdByRole('Taniye'),
        legacyPersona: {
          name: 'Taniye',
          description: 'Workflow orchestration agent',
          capabilities: ['workflow-management', 'task-orchestration'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'intermediate',
          contextWindowSize: 6000,
          decisionThreshold: 0.85,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'high',
          allowedCapabilities: ['workflow-management'],
          restrictedDomains: [],
          approvalRequired: true,
          auditLevel: 'comprehensive',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: [
          'workflow-management',
          'task-orchestration',
          'process-automation',
          'scheduling',
        ],
        capabilityScores: { 'workflow-management': 0.93, 'task-orchestration': 0.91 },
        performanceMetrics: { averageResponseTime: 1.8, successRate: 0.96, userSatisfaction: 0.92 },
        securityLevel: 'high',
        complianceTags: ['WORKFLOW', 'AUTOMATION'],
        configuration: { maxConcurrentOperations: 10, timeoutDuration: 600, retryAttempts: 3 },
        version: '1.8.2',
        deploymentEnvironment: 'production',
        totalOperations: 3456,
        successfulOperations: 3318,
        averageResponseTime: 1.8,
        modelId: 'deepcogito-v1',
        apiType: 'llmstudio',
        temperature: 0.4,
        maxTokens: 3000,
        systemPrompt: 'You are Taniye, a master of workflow management.',
        maxConcurrentTools: 8,
      },
      {
        name: 'Prashis',
        role: AgentRole.EXECUTOR,
        personaId: this.getPersonaIdByRole('Prashis'),
        legacyPersona: {
          name: 'Prashis',
          description: 'Full-stack engineer',
          capabilities: ['full-stack-development', 'api-design'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'intermediate',
          contextWindowSize: 6000,
          decisionThreshold: 0.75,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'medium',
          allowedCapabilities: ['full-stack-development'],
          restrictedDomains: [],
          approvalRequired: false,
          auditLevel: 'standard',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: ['full-stack-development', 'api-design', 'database-optimization', 'testing'],
        capabilityScores: { 'full-stack-development': 0.88, 'api-design': 0.85 },
        performanceMetrics: { averageResponseTime: 2.2, successRate: 0.91, userSatisfaction: 0.87 },
        securityLevel: 'medium',
        complianceTags: ['CODE_QUALITY', 'TESTING'],
        configuration: { maxConcurrentOperations: 6, timeoutDuration: 300, retryAttempts: 3 },
        version: '1.5.1',
        deploymentEnvironment: 'production',
        totalOperations: 2890,
        successfulOperations: 2630,
        averageResponseTime: 2.2,
        modelId: 'smollm3-3b',
        apiType: 'llmstudio',
        temperature: 0.4,
        maxTokens: 3500,
        systemPrompt: 'You are Prashis, a skilled full-stack engineer.',
        maxConcurrentTools: 6,
      },
      {
        name: 'Keegan',
        role: AgentRole.EXECUTOR,
        personaId: this.getPersonaIdByRole('Keegan'),
        legacyPersona: {
          name: 'Keegan',
          description: 'Backend systems expert',
          capabilities: ['backend-development', 'system-architecture'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'advanced',
          contextWindowSize: 7000,
          decisionThreshold: 0.8,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'high',
          allowedCapabilities: ['backend-development'],
          restrictedDomains: [],
          approvalRequired: true,
          auditLevel: 'comprehensive',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: [
          'backend-development',
          'system-architecture',
          'performance-tuning',
          'security',
        ],
        capabilityScores: { 'backend-development': 0.92, 'system-architecture': 0.89 },
        performanceMetrics: { averageResponseTime: 1.9, successRate: 0.93, userSatisfaction: 0.9 },
        securityLevel: 'high',
        complianceTags: ['SECURITY', 'PERFORMANCE', 'SCALABILITY'],
        configuration: { maxConcurrentOperations: 4, timeoutDuration: 450, retryAttempts: 3 },
        version: '2.0.3',
        deploymentEnvironment: 'production',
        totalOperations: 1876,
        successfulOperations: 1745,
        averageResponseTime: 1.9,
        modelId: 'smollm3-3b',
        apiType: 'llmstudio',
        temperature: 0.3,
        maxTokens: 4000,
        systemPrompt: 'You are Keegan, a backend systems expert.',
        maxConcurrentTools: 5,
      },
      {
        name: 'Josh',
        role: AgentRole.EXECUTOR,
        personaId: this.getPersonaIdByRole('Josh'),
        legacyPersona: {
          name: 'Josh',
          description: 'Frontend specialist',
          capabilities: ['frontend-development', 'ui-ux-design'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'intermediate',
          contextWindowSize: 5500,
          decisionThreshold: 0.72,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'medium',
          allowedCapabilities: ['frontend-development'],
          restrictedDomains: [],
          approvalRequired: false,
          auditLevel: 'standard',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: [
          'frontend-development',
          'ui-ux-design',
          'responsive-design',
          'accessibility',
        ],
        capabilityScores: { 'frontend-development': 0.9, 'ui-ux-design': 0.86 },
        performanceMetrics: { averageResponseTime: 2.1, successRate: 0.89, userSatisfaction: 0.91 },
        securityLevel: 'medium',
        complianceTags: ['ACCESSIBILITY', 'UX', 'RESPONSIVE'],
        configuration: { maxConcurrentOperations: 7, timeoutDuration: 250, retryAttempts: 2 },
        version: '1.7.2',
        deploymentEnvironment: 'production',
        totalOperations: 3245,
        successfulOperations: 2888,
        averageResponseTime: 2.1,
        modelId: 'smollm3-3b',
        apiType: 'llmstudio',
        temperature: 0.5,
        maxTokens: 3200,
        systemPrompt: 'You are Josh, a frontend developer focused on UX.',
        maxConcurrentTools: 7,
      },
      {
        name: 'Pankaj',
        role: AgentRole.EXECUTOR,
        personaId: this.getPersonaIdByRole('Pankaj'),
        legacyPersona: {
          name: 'Pankaj',
          description: 'DevOps engineer',
          capabilities: ['devops', 'infrastructure-automation'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'advanced',
          contextWindowSize: 6500,
          decisionThreshold: 0.85,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'high',
          allowedCapabilities: ['devops'],
          restrictedDomains: [],
          approvalRequired: true,
          auditLevel: 'comprehensive',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: ['devops', 'infrastructure-automation', 'monitoring', 'deployment'],
        capabilityScores: { devops: 0.94, 'infrastructure-automation': 0.91 },
        performanceMetrics: { averageResponseTime: 1.7, successRate: 0.96, userSatisfaction: 0.93 },
        securityLevel: 'high',
        complianceTags: ['INFRASTRUCTURE', 'AUTOMATION', 'MONITORING'],
        configuration: { maxConcurrentOperations: 8, timeoutDuration: 600, retryAttempts: 5 },
        version: '2.2.1',
        deploymentEnvironment: 'production',
        totalOperations: 2156,
        successfulOperations: 2070,
        averageResponseTime: 1.7,
        modelId: 'deepcogito-v1',
        apiType: 'llmstudio',
        temperature: 0.2,
        maxTokens: 3800,
        systemPrompt: 'You are Pankaj, a DevOps expert.',
        maxConcurrentTools: 8,
      },
      {
        name: 'Maya',
        role: AgentRole.ADVISOR,
        personaId: this.getPersonaIdByRole('Maya'),
        legacyPersona: {
          name: 'Maya',
          description: 'Creative director',
          capabilities: ['creative-direction', 'brand-strategy'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'advanced',
          contextWindowSize: 7500,
          decisionThreshold: 0.7,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'medium',
          allowedCapabilities: ['creative-direction'],
          restrictedDomains: [],
          approvalRequired: false,
          auditLevel: 'standard',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: ['creative-direction', 'brand-strategy', 'design-systems', 'user-research'],
        capabilityScores: { 'creative-direction': 0.95, 'brand-strategy': 0.88 },
        performanceMetrics: { averageResponseTime: 3.2, successRate: 0.87, userSatisfaction: 0.94 },
        securityLevel: 'medium',
        complianceTags: ['CREATIVE', 'BRAND', 'UX'],
        configuration: { maxConcurrentOperations: 4, timeoutDuration: 400, retryAttempts: 2 },
        version: '1.3.0',
        deploymentEnvironment: 'production',
        totalOperations: 1567,
        successfulOperations: 1363,
        averageResponseTime: 3.2,
        modelId: 'arch-agent-7b-i1',
        apiType: 'llmstudio',
        temperature: 0.8,
        maxTokens: 4200,
        systemPrompt: 'You are Maya, a visionary creative director.',
        maxConcurrentTools: 5,
      },
      {
        name: 'Zara',
        role: AgentRole.ADVISOR,
        personaId: this.getPersonaIdByRole('Zara'),
        legacyPersona: {
          name: 'Zara',
          description: 'Behavioral psychologist',
          capabilities: ['behavioral-analysis', 'user-psychology'],
          constraints: {},
          preferences: {},
        } as AgentPersona,
        intelligenceConfig: {
          analysisDepth: 'advanced',
          contextWindowSize: 8500,
          decisionThreshold: 0.75,
          learningEnabled: true,
          collaborationMode: 'collaborative',
        } as AgentIntelligenceConfig,
        securityContext: {
          securityLevel: 'high',
          allowedCapabilities: ['behavioral-analysis'],
          restrictedDomains: ['personal-data'],
          approvalRequired: true,
          auditLevel: 'comprehensive',
        } as AgentSecurityContext,
        isActive: true,
        createdBy: this.users[0]?.id || '00000000-0000-0000-0000-000000000000',
        lastActiveAt: new Date(),
        capabilities: [
          'behavioral-analysis',
          'user-psychology',
          'team-dynamics',
          'empathy-mapping',
        ],
        capabilityScores: { 'behavioral-analysis': 0.93, 'user-psychology': 0.96 },
        performanceMetrics: { averageResponseTime: 3.8, successRate: 0.92, userSatisfaction: 0.96 },
        securityLevel: 'high',
        complianceTags: ['PSYCHOLOGY', 'ETHICS', 'PRIVACY'],
        configuration: { maxConcurrentOperations: 3, timeoutDuration: 500, retryAttempts: 2 },
        version: '1.4.2',
        deploymentEnvironment: 'production',
        totalOperations: 987,
        successfulOperations: 908,
        averageResponseTime: 3.8,
        modelId: 'deepcogito-v1',
        apiType: 'llmstudio',
        temperature: 0.6,
        maxTokens: 4500,
        systemPrompt: 'You are Zara, a behavioral psychologist.',
        maxConcurrentTools: 4,
      },
    ];
  }
}
