name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity. 
          It will be closed if no further activity occurs. Thank you for your contributions.
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity. 
          It will be closed if no further activity occurs. Thank you for your contributions.
        close-issue-message: |
          This issue was closed because it has been stalled for 7 days with no activity.
        close-pr-message: |
          This pull request was closed because it has been stalled for 7 days with no activity.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned,security,bug,enhancement'
        exempt-pr-labels: 'pinned,security,work-in-progress'
        days-before-stale: 30
        days-before-close: 7
        operations-per-run: 30 